version: '3.4'

services:
  marc-service:
    container_name: marc-service
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "80:8080"
    links: 
      - "mongo"
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"